apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: camel-instrumentation
spec:
  exporter:
    endpoint: 'http://otel-example-collector-headless:4318'
  java:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.19.0'
    env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: 'metadata.labels[''app'']'
      - name: OTEL_TRACER_SAMPLER
        value: always_on
      - name: OTEL_LOGS_EXPORTER
        value: none
      - name: OTEL_JMX_TARGET_SYSTEM
        value: camel
      - name: OTEL_INSTRUMENTATION_APACHE_HTTPCLIENT_ENABLED
        value: 'false'
      - name: OTEL_INSTRUMENTATION_UNDERTOW_ENABLED
        value: 'false'
      - name: OTEL_INSTRUMENTATION_SERVLET_ENABLED
        value: 'false'