apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempo-traces-reader
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - application
    resourceNames:
      - traces
    verbs:
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempo-traces-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempo-traces-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempo-traces-write
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - application
    resourceNames:
      - traces
    verbs:
      - 'create'
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: otel-collector
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tempo-traces-from-otel
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: otel-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempo-traces-write