apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-example-collector
spec:
  endpoints:
    - interval: 30s
      port: promexporter
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name:  obs-example-collector