apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: @project.artifactId@-edit
roleRef:
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: @project.artifactId@
