apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: @project.artifactId@
    group: @project.groupId@
    provider: jkube
    statefulset.kubernetes.io/pod-name: @project.artifactId@-1
  type: ClusterIP
