apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "@project.artifactId@-view"
roleRef:
  kind: ClusterRole
  name: "view"
subjects:
  - kind: ServiceAccount
    name: @project.artifactId@
