apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: csb-examples
spec:
  groups:
    - name: csb-examples
      rules:
        - alert: ObservationClientError
          annotations:
            summary: Check client error within latest 60 seconds.
            message: There are some errors on the client!
          expr: changes(camel_exchanges_failed_total{service="otel-example-collector-headless",eventType="route", camelContext="client"}[60s]) > 0
          for: 10s
          labels:
            severity: critical
